apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_USER: "itam_app_user"
  POSTGRES_PASSWORD: "CHANGE_ME_IN_PRODUCTION_ENV_SECRET"
  ANTHROPIC_API_KEY: "sk-ant-api03-mock-vault-key"
  S3_ACCESS_KEY: "AKIA_MOCK_ENTERPRISE_ITAM_KEY"
  S3_SECRET_KEY: "MOCK_ENTERPRISE_SECRET_KEY_FOR_K8S"
