apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app.kubernetes.io/name: itam-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: itam-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-copilot
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app.kubernetes.io/name: itam-copilot
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.copilot.service.type }}
  ports:
    - port: {{ .Values.copilot.service.port }}
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: itam-copilot
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-storage
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app.kubernetes.io/name: itam-storage
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.storage.service.type }}
  ports:
    - port: {{ .Values.storage.service.port }}
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: itam-storage
    app.kubernetes.io/instance: {{ .Release.Name }}
