apiVersion: v2
name: itam
description: Reusable Helm Chart for Enterprise ITAM & CMDB SaaS Application Deployment on Managed Kubernetes (EKS, AKS, GKE, On-Prem)
type: application
version: 1.0.0
appVersion: "2026.8.0"
keywords:
  - itam
  - cmdb
  - asset-management
  - enterprise
  - kubernetes
  - helm
maintainers:
  - name: Platform Engineering Team
    email: devops@enterprise-itam.internal
annotations:
  category: Enterprise ITAM SaaS
