import React, { useEffect, useState } from 'react';
import { AlertTriangle, Network, Play, RefreshCw } from 'lucide-react';

type Job = { id: string; targetCidr: string; status: string; devicesScanned: number; devicesFound: number; newCis: number; updatedCis: number; startTime: string };

/** A display-only console: all network activity happens in an enrolled scanner. */
export const AgentlessDiscoveryModule: React.FC = () => {
  const [jobs, setJobs] = useState<Job[]>([]); const [cidr, setCidr] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const tenantId = localStorage.getItem('tenantId') || '';
  const load = async () => { setLoading(true); try { const r = await fetch('/api/discovery/jobs', { headers: tenantId ? { 'X-Tenant-ID': tenantId } : {} }); if (!r.ok) throw new Error('Unable to load discovery status'); const d = await r.json(); setJobs(d.jobs || []); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load discovery status'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const start = async () => { setError(''); if (!cidr.trim()) return setError('Enter a client-authorized CIDR range.'); try { const r = await fetch('/api/discovery/agentless/sweep', { method: 'POST', headers: { 'Content-Type': 'application/json', ...(tenantId ? { 'X-Tenant-ID': tenantId } : {}) }, body: JSON.stringify({ cidr, protocols: ['ICMP', 'TCP'] }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Unable to queue scan'); setCidr(''); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to queue scan'); } };
  return <div className="p-6 space-y-6"><div className="flex justify-between items-center"><div><h1 className="text-xl font-semibold flex items-center gap-2"><Network /> Agentless Discovery</h1><p className="text-sm text-slate-500">Scans run only through an enrolled scanner inside your network.</p></div><button onClick={() => void load()} className="btn-secondary"><RefreshCw className="w-4 h-4" /> Refresh</button></div><div className="rounded-lg border p-4 space-y-3"><label className="block text-sm font-medium">Authorized network / subnet</label><div className="flex gap-2"><input value={cidr} onChange={e => setCidr(e.target.value)} placeholder="Configured CIDR, e.g. 10.10.10.0/24" className="flex-1 border rounded px-3 py-2"/><button onClick={() => void start()} className="btn-primary"><Play className="w-4 h-4"/> Queue scan</button></div><p className="text-xs text-slate-500">The scanner validates its own approved ranges and uploads actual results. A queued scan is not a completed scan.</p>{error && <p className="text-sm text-red-600 flex gap-2"><AlertTriangle className="w-4 h-4"/>{error}</p>}</div>{loading ? <p>Loading discovery status…</p> : jobs.length === 0 ? <div className="rounded-lg border border-dashed p-8 text-center"><p className="font-medium">Discovery is not configured</p><p className="text-sm text-slate-500">Enroll a scanner, configure an approved network, then queue the first scan.</p></div> : <table className="w-full text-sm"><thead><tr className="text-left border-b"><th>Scan</th><th>Target</th><th>Status</th><th>Targets</th><th>Discovered</th><th>New / Updated</th></tr></thead><tbody>{jobs.map(j => <tr key={j.id} className="border-b"><td>{j.id}</td><td>{j.targetCidr}</td><td>{j.status}</td><td>{j.devicesScanned}</td><td>{j.devicesFound}</td><td>{j.newCis} / {j.updatedCis}</td></tr>)}</tbody></table>}</div>;
};
export default AgentlessDiscoveryModule;
