apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: itam-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/enterprise-org/itam-saas.git'
    targetRevision: HEAD
    path: helm/itam
    helm:
      valueFiles:
        - ../../gitops/environments/staging/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: itam-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
